### PR TITLE
Adding CI/CD best practice

### PR DESCRIPTION
**Pull request by amirfried**

### CODE REVIEW

**Comment by bregman-arie** [comment]
By short you mean definition length or the time it takes to run?

**Comment by amirfried** [comment]
> By short you mean definition length or the time it takes to run?

Yes. When a developer commit/merge, pipeline should provide fast feedback. Developer should not wait for hours/days to find out that something is wrong. For example, tests should run as fast as possible. This can be done by "shifting left" tests or/and with tools like https://www.sealights.io/product/test-impact-analysis/.

**Comment by bregman-arie** [comment]
> > By short you mean definition length or the time it takes to run?
> 
> Yes. When a developer commit/merge, pipeline should provide fast feedback. Developer should not wait for hours/days to find out that something is wrong. For example, tests should run as fast as possible. This can be done by "shifting left" tests or/and with tools like https://www.sealights.io/product/test-impact-analysis/.

I agree. In this case maybe you repharse it little bit. Either saying fast feedback or short execution time. Because right now it it's little bit obscure.

**Comment by amirfried** [comment]
> 

Thanks for the comment. I have rephrased.

**Review by bregman-arie — APPROVED** [review]

**Comment by bregman-arie** [comment]
Thanks for making the changes. Merging.

**Pull request merged**
