### PR TITLE
Added handy devops resourses

### PR DESCRIPTION
**Pull request by falconcode16**
Added useful beginner friendly DevOps starter pack as in form of images which are quite handy.

The resource contain notes on - 
1. Server Administration
2. Networking and security
3. Servers
4. Infrastructure as code
5. CI/CD
6. Monitoring and logging

### CODE REVIEW

**Comment by bregman-arie** [comment]
Did you prepare these slides? if not, attribution should be mentioned
Also, you might want to change the files names..."Screenshot ..." is not meaningful enough.

**Comment by falconcode16** [comment]
Okay I will name each and every slide making it easier to access.

**Comment by falconcode16** [comment]
Hey Arie, I have made changes in the file name with appropriate names.

Attribute: DevOps Tutorial for Beginners, Edureka
Link: https://www.youtube.com/watch?v=hQcFE0RD0cQ&t=20199s

**Comment by bregman-arie** [comment]
@falconcode16 I'm sorry but I can't merge this change. Resources belong to Edureka.

**Comment by falconcode16** [comment]
No problem, thanks!

**Pull request closed without merging**
